name: SonarQube analysis

on: [pull_request]

jobs:
  sonarqube:
    runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build
        run: mvn -f dhis-2/pom.xml clean install -Psonarqube
      - name: Analyse
        env:
          BASE_BRANCH: ${{ github.base_ref }}
          BRANCH: ${{ github.ref }}
          PR: ${{ github.event.number }}
        run: mvn -f dhis-2/pom.xml sonar:sonar
          -Dsonar.pullrequest.key=${PR}
          -Dsonar.pullrequest.branch=${BRANCH}
          -Dsonar.pullrequest.base=${BASE_BRANCH}
