name: Integration test

on: [pull_request]

jobs:
  integration-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run integration tests
      run: mvn clean install -Pintegration -f ./dhis-2/pom.xml
    
