name: Test

on: [pull_request]

jobs:
  cleanup-runs:
    runs-on: ubuntu-latest
    steps:
    - uses: rokroskar/workflow-run-cleanup-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/master'"
      
  api-test:
    env:
      CORE_IMAGE_NAME: "dhis2/core-dev:local"
      TEST_IMAGE_NAME: "dhis2/tests:local"
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'run-api-tests')
    steps:
    - uses: actions/checkout@v2
    - name: Build core image
      run: |
        docker build . -t $CORE_IMAGE_NAME
        ./docker/extract-artifacts.sh $CORE_IMAGE_NAME
        ONLY_DEFAULT=1 ./docker/build-containers.sh $CORE_IMAGE_NAME $CORE_IMAGE_NAME

    - name: Run tests
      run: |
        cd dhis-2/dhis-e2e-test
        IMAGE_NAME=$CORE_IMAGE_NAME docker-compose up -d
        docker build -t $TEST_IMAGE_NAME .
        IMAGE_NAME=$TEST_IMAGE_NAME docker-compose -f docker-compose.e2e.yml up --exit-code-from e2e-test

    - name: Upload logs
      run: |
        docker-compose logs web > logs.txt
      - uses: actions/upload-artifact@v2
        with:
          path: logs.txt

