name: Run tests

on: [pull_request]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Test core
      run: mvn clean install -DskipTests=false --update-snapshots -q -f ./dhis-2/pom.xml
    - name: Test dhis-web
      run: mvn clean install -DskipTests=false --update-snapshots -q -f ./dhis-2/dhis-web/pom.xml

  integration-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run integration tests
      run: mvn clean install -Pintegration -f ./dhis-2/pom.xml