name: Test

on: [pull_request]

jobs:
  cleanup-runs:
    runs-on: ubuntu-latest
    steps:
    - uses: rokroskar/workflow-run-cleanup-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/master'"
      
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Test core
      run: mvn clean install -DskipTests=false --update-snapshots -q -f ./dhis-2/pom.xml
    - name: Test dhis-web
      run: mvn clean install -DskipTests=false --update-snapshots -q -f ./dhis-2/dhis-web/pom.xml
  
  integration-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Run integration tests
      run: mvn clean install -Pintegration -f ./dhis-2/pom.xml
    
  api-test:
    env:
      CORE_IMAGE_NAME: "dhis2/core:local"
      TEST_IMAGE_NAME: "dhis2/tests:local"
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'run-api-tests')
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Build core image
      run: |
        bash ./dhis-2/build-dev.sh

    - name: Run tests
      run: |
        cd dhis-2/dhis-e2e-test
        IMAGE_NAME=$CORE_IMAGE_NAME docker-compose up -d
        docker build -t $TEST_IMAGE_NAME .
        IMAGE_NAME=$TEST_IMAGE_NAME docker-compose -f docker-compose.e2e.yml up --exit-code-from e2e-test

    - name: Upload logs
      if: failure()
      run: |
        cd dhis-2/dhis-e2e-test
        docker-compose logs web > ~/logs.txt

    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: "logs"
        path: '~/logs.txt'
